### PR TITLE
refresh metadata on connection error when listing topics

### PR DESCRIPTION
**Pull request by ttamimi**

### CODE REVIEW

**Comment by dasch** [comment]
Can you look into fixing the failing specs? Then I'll happily merge.

**Comment by ttamimi** [comment]
Sure, I'll fix the specs.
Thanks

**Comment by dasch** [comment]
Rebasing on master may fix it.

**Comment by ttamimi** [comment]
Created a new PR after rebasing branch onto master
https://github.com/zendesk/ruby-kafka/pull/644

**Pull request closed without merging**
