### PR TITLE
fix ssl socket timeout

### PR DESCRIPTION
**Pull request by tcrayford**
We've been seeing a case where Kafka won't accept new SSL connections
properly. It accepts the TCP one, but doesn't perform the SSL handshake
properly. The SSL socket behaviour in this library doesn't handle this
case properly.

This clears up the logic in this class as well to use a
`select_with_timeout` method (taken from
https://github.com/excon/excon/blob/192bb842e70b550ed6d78c6d621962ee0faca4be/lib/excon/socket.rb)

I've tested this against a broken production Kafka and this does indeed get a proper timeout.

### CODE REVIEW

**Comment by dasch** [comment]
:heart:

**Comment by tcrayford** [comment]
@dasch can we get a release with this fix in it?

**Comment by dasch** [comment]
Unfortunately I'm on leave and won't be back until December – since I haven't been able to find anyone willing to co-maintain the library in the only one with push access :-/

Not sure if it's possible to add a maintainer without terminal access...

**Comment by dasch** [comment]
@tcrayford I've released v0.3.16.beta1 – I'd love for you guys to give it a spin before I release a final version.

**Comment by tcrayford** [comment]
@dasch we've been running with the commit 39dd97c5a793de81357567936bb1f41f8cf567dc (which includes this PR) in production for aages now, I think it'll be fine.

**Comment by dasch** [comment]
:heart:

**Comment by dasch** [comment]
I'll probably cut a final release this week, then.

**Pull request merged**
