### PR TITLE
AWS MSK IAM auth

### PR DESCRIPTION
**Pull request by kirkokada**
I am opening up this PR to expand on the work that @jobeus started in https://github.com/zendesk/ruby-kafka/pull/907 since it has been over a month since the last update. If the maintainers prefer, feel free to fold these updates into the original PR.

Updates from the original PR:
* Added session token to the IAM mechanism. This is necessary for auth via temporary credentials such as those returned when assuming a role.
* Fixed broken unit tests

### CODE REVIEW

**Comment by jobeus** [comment]
This looks great to me but I have no merge powers and I haven't gotten a response from anyone at Zendesk since August last year? I know I had to fix the unit tests I was just hoping for some sort of reply and got tired of checking here and missed your interaction, @kirkokada, sorry!

**Comment by dasch** [comment]
Hey, sorry for the delays in response! The tests failed for some versions of Kafka – I'll re-run them and see if that works.

**Comment by dasch** [comment]
Still getting failures – can you try to run this locally? I haven't looked at the CI suite in ages, not sure if it's still fully reliable.

**Comment by dasch** [comment]
I've re-run the specs many times, still trying to get the last one to pass. If anyone's looking for a way to contribute, modernizing the test suite would be a good starting point!

**Comment by kirkokada** [comment]
I've run the failing test locally and it also fails. It is also failing on master.

**Comment by kirkokada** [comment]
There seems to be a problem with the image: https://github.com/wurstmeister/kafka-docker/issues/669

**Comment by kirkokada** [comment]
The test suite passes locally if I run it against a cluster using the `bitnami/kafka:2.7.0` image. I could try to update the circle-ci configs in this PR but that seems better suited for it's own PR. 

@dasch what do you think?

**Comment by dasch** [comment]
@kirkokada that would be great!

**Comment by kirkokada** [comment]
@dasch I went ahead and just updated the circleci configs in this branch. The previously failing test appears to be passing but the other jobs need to be rerun

**Comment by kirkokada** [comment]
@dasch PR to update circle ci/tests here: https://github.com/zendesk/ruby-kafka/pull/939

**Comment by patelvp** [comment]
This is awsome!!

**Pull request merged**
