### PR TITLE
add kafka 2.2.1 to CI

### PR DESCRIPTION
**Pull request by vvuibert**
- add kafka `2.2.1`
- update `2.1.0` to `2.1.1`

### CODE REVIEW

**Comment by sam-obeid** [comment]
+1

**Comment by Elyahou** [comment]
Is there any issue with 2.3?

**Comment by vvuibert** [comment]
@Elyahou yes the tests failed for `2.3`
https://circleci.com/gh/zendesk/ruby-kafka/3873?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by dasch** [comment]
Thanks!

**Pull request merged**
