### PR TITLE
Support the topic creation API

### PR DESCRIPTION
**Pull request by dasch**
Requires Kafka 0.10.2+

### CODE REVIEW

**Comment by mensfeld** [comment]
Don't forget about updating README :dancing_men:  :D

**Comment by dasch** [comment]
I need to update the test infrastructure to Kafka 0.11 first...

**Comment by tcrayford** [comment]
@dasch technically 0.10.2 or so iirc supports this API as well, but there are a lot more admin apis in 0.11 that are very useful.

**Comment by dasch** [comment]
@tcrayford good to know! I'm tracking the 0.11 API support [in this project](https://github.com/zendesk/ruby-kafka/projects/3).

**Comment by dasch** [comment]
@tcrayford it seems that [Kafka 0.10.1.0](https://archive.apache.org/dist/kafka/0.10.1.0/RELEASE_NOTES.html) was the first release with support for this API. I'm thinking about making that the minimum required version for ruby-kafka in order to not have to provide support for multiple versions of the metadata API just yet. Do you have any sense of how many people are still using previous versions of 0.10?

**Comment by tcrayford** [comment]
@dasch only on heroku really, and we've been pushing folk off older 0.10 releases because of other bugs.

**Comment by dasch** [comment]
@tcrayford I'm going to see how difficult it would be to support multiple versions...

**Pull request merged**
