### PR TITLE
Validate the URI scheme of seed brokers

### PR DESCRIPTION
**Pull request by dasch**
Due to #415 I think it would be an improvement to UX if we validate these URIs at setup time.

### CODE REVIEW

**Comment by dasch** [comment]
@tcrayford is this the correct scheme for Heroku?

**Comment by mensfeld** [comment]
@dasch shouldn't it be a higher level lib responsibility like racecar or Karafka to validate things like that?

**Comment by dasch** [comment]
They can rescue the exception and provide a nice error message, but ruby-kafka should catch the misconfiguration early.

**Comment by dasch** [comment]
Note that, if more schemes were allowed in the future, the high-level libraries shouldn't have to care – it's the responsibility of ruby-kafka to turn those connection strings into actual connections.

**Pull request merged**
