### PR TITLE
Add Consumer#seek

### PR DESCRIPTION
**Pull request by ale7714**

### CODE REVIEW

**Comment by dasch** [comment]
:heart:

**Comment by mensfeld** [comment]
@dasch  will there be a doc or a description on the #seek in the docs? Thanks in advance.

**Comment by dasch** [comment]
@mensfeld yup, I'll add documentation for this.

**Comment by dasch** [comment]
@mensfeld https://github.com/zendesk/ruby-kafka/commit/0c94672c626d03a863b5a721cc47a75873bd466c

**Comment by mensfeld** [comment]
@dasch  thank you (as always!)

**Comment by ale7714** [comment]
@dasch thanks for merging and adding docs 🎉

**Pull request merged**
