### PR TITLE
Specify that the gem doesn't work with Active Support 6

### PR DESCRIPTION
**Pull request by dasch**

### CODE REVIEW

**Comment by mensfeld** [comment]
@dasch what is the problem with AS6?

**Comment by dasch** [comment]
@mensfeld there was a [regression in CI](https://circleci.com/gh/zendesk/ruby-kafka/4012).

```
     NoMethodError:
       undefined method `monotonic_time' for Concurrent:Module
     # ./vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:140:in `now'
     # ./vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:79:in `start!'
     # ./vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/subscriber.rb:132:in `start'
     # ./vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications/fanout.rb:156:in `start'
     # ./vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications/fanout.rb:58:in `block in start'
     # ./vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications/fanout.rb:58:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications/fanout.rb:58:in `start'
     # ./vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:36:in `start'
     # ./vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:22:in `instrument'
     # ./vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `instrument'
     # ./lib/kafka/instrumenter.rb:21:in `instrument'
     # ./lib/kafka/connection.rb:97:in `send_request'
     # ./lib/kafka/broker.rb:200:in `send_request'
     # ./lib/kafka/broker.rb:44:in `fetch_metadata'
     # ./lib/kafka/cluster.rb:409:in `block in fetch_cluster_info'
     # ./lib/kafka/cluster.rb:404:in `each'
     # ./lib/kafka/cluster.rb:404:in `fetch_cluster_info'
     # ./lib/kafka/cluster.rb:384:in `cluster_info'
     # ./lib/kafka/cluster.rb:446:in `controller_broker'
     # ./lib/kafka/cluster.rb:197:in `create_topic'
     # ./lib/kafka/client.rb:572:in `create_topic'
     # ./spec/spec_helper.rb:66:in `create_topic'
     # ./spec/spec_helper.rb:61:in `create_random_topic'
     # ./spec/functional/async_producer_spec.rb:5:in `block (2 levels) in <top (required)>'
```

**Comment by dasch** [comment]
Merging this for now, as the test suite is otherwise broken, but we need a fix for this issue.

**Comment by mensfeld** [comment]
sidenote: that's why things like AS should not be part of RK. We should just have a general interface with a AS api.

**Comment by dasch** [comment]
It's a soft dependency. I'd rather if ActiveSupport::Notifications was extracted to a separate gem, though.

**Pull request merged**
