### PR TITLE
Report consumer lag to StatsD when processing batches

### PR DESCRIPTION
**Pull request by Elyahou**
Is it possible to merge this to 0.4.x release too ?

### CODE REVIEW

**Comment by dasch** [comment]
❤️ 

I'll cherry-pick this to the 0.4 branch as well.

**Comment by Shadowssong** [comment]
@dasch Did this get into 0.4.3 or any 0.4.x release?  It says its included in the changelog but the v0.4.3 branch is missing this change.  Thanks!

**Comment by dasch** [comment]
@Shadowssong there hasn't been a release of v0.4.x since the cherry pick. I won't release that series very often, as the main line of development is now v0.5.

**Comment by Shadowssong** [comment]
@dasch Gotcha thanks for the update, may be worth removing this change from the 0.4.3 release changelog then https://github.com/zendesk/ruby-kafka/blame/master/CHANGELOG.md#L22
Thanks for all your great work btw!

**Comment by dasch** [comment]
I've released v0.4.4 with the latest changes.

**Pull request merged**
