### PR TITLE
don't re-commit offsets on idle.

### PR DESCRIPTION
**Pull request by osheroff**
Since we never clear @processed_offsets, we should check that we're actually moving forward on a partition before bothering to commit it.

### CODE REVIEW

**Comment by dasch** [comment]
Is the rate of commits causing problems?

**Comment by osheroff** [comment]
no, just kinda annoying.  at idle all my consumers re-commit the same offset over and over and over again.  I don't know what the cost is server side, but I'd imagine it's non-zero with a decent amount of consumers.

**Comment by osheroff** [comment]
(man, that was the most wishy-washy statement ever.  "i'd imagine it's non-zero".  sheesh.)

**Comment by dasch** [comment]
I'd rather not mess too much with the checkpointing code while I'm away - it's been a source of many a bug. Let me look at this when I'm back.

**Pull request closed without merging**
