### PR TITLE
#618: Move heartbeat processing to a separate thread

### PR DESCRIPTION
**Pull request by dorner**
See issue #618. Comments and suggestions are welcome - please tear this apart! 😬

### CODE REVIEW

**Comment by dasch** [comment]
I'd like to get this functionality, but I want to avoid using a mutex to achieve it. The problem of course is that the heartbeats need to be sent on the same socket as the other group API calls, so we do need to synchronize access to that socket.

One way to go about this would be to run the consumer group client code in a wholly separate thread and use a thread-safe queue to communicate with the processing code. That's one reason I've been hesitant to add support for background heartbeats – doing it properly is hard.

**Comment by dasch** [comment]
Also note that the CI tests are failing.

**Comment by dorner** [comment]
@dasch thanks for the feedback. Can you explain more why you don't think a mutex will work? We've had this in production for about 2 weeks now and have not seen any problems.
I can fix the tests - silly last minute update which I did without checking.

**Comment by dasch** [comment]
@dorner my worry is about long-term maintenance – debugging deadlocks and other mutex-related issues is very hard, so I'm wary about introducing such concepts. If we were to do it, I'd prefer the mutex live in `Connection` if that could be done in a performant way. Sprinkling locks throughout the code base is a recipe for future disaster.

**Comment by mensfeld** [comment]
I agree with @dasch. Ruby Kafka already has concurrency and more than one thread. Introducing new multi thread dependencies will be a nightmare during debugging and error finding. I still recall the separate thread prefetch memory bloats that we had ;)

**Comment by dorner** [comment]
@dasch OK, makes sense. From your previous comment - moving all consumer group functionality to a separate thread - do you have a high level description of how that might be implemented? I can take the time to try and do the work on my end. Would it be similar to how Fetcher is done right now?

Also, OTOH would that include heartbeat, join_group and synchronize? Anything else?

**Comment by dasch** [comment]
@dorner it's a rather large and risky change, and would probably involve multiple rounds of explorative implementation.

A simpler approach might be to start by moving the _processing_ to another thread, which would leave the main thread responsible for the group stuff. A `Queue` could be used to send messages to the processor thread, and another one could be used to send back acknowledgements or errors. It may or may not work well in practice.

**Comment by dorner** [comment]
@dasch well, I'm willing to take whatever approach you feel is best. That one sounds even messier to me though - we'd have to move from a consumer loop to something more of a cross-thread communication (since we can't move on to the next message until the current message is finished processing). Unless I'm misunderstanding your suggestion?

**Comment by dasch** [comment]
Nah, that's exactly right. But finding the right design here is messy – there are a lot of moving pieces.

**Comment by dasch** [comment]
I just got a feeling that the number of interactions in the group code will
make it harder, but feel free to give it a go!

Note though that I’ll only merge the resulting code if it’s sufficiently
maintainable - I personally implemented an async IO system for ruby-kafka
but ended up reverting it because it proved too unstable and difficult to
debug...

**Pull request closed without merging**
