### PR TITLE
Less static CI setup

### PR DESCRIPTION
**Pull request by bquorning**
Using static versions of Ruby, Bundler and other gems, there's more to manually keep up to date.

### CODE REVIEW

**Comment by dasch** [comment]
@bquorning this doesn't seem to pass CI, I've tried restarting it twice.

**Comment by bquorning** [comment]
I’ll try splitting the changes in one commit each so the can run on CI independent of each other.

**Comment by bquorning** [comment]
It looks like this gem (or at least one spec) is not compatible with dogstatsd-ruby v3.0.0: https://github.com/DataDog/dogstatsd-ruby/blob/master/CHANGELOG.md

**Comment by dasch** [comment]
@bquorning let me see if I can fix that.

**Comment by dasch** [comment]
Try rebasing on top of master and removing the statsd stuff.

**Comment by bquorning** [comment]
Done

**Comment by dasch** [comment]
:heart:

**Pull request merged**
