### PR TITLE
move sleep values to constant

### PR DESCRIPTION
**Pull request by nijikon**
As a first step of making sleep values configurable move them to constants.

### CODE REVIEW

**Comment by nijikon** [comment]
@dasch we can change the key names to whatever you think is better

**Comment by dasch** [comment]
I'd rather move the constant to `Kafka::DEFAULT_BACKOFFS`. But maybe include the full change in this PR?

**Comment by nijikon** [comment]
@dasch we can move it to `Kafka::DEFAULT_BACKOFFS`, that's even better. I would rather create small changes instead of creating a big PR which is hard to review, and if for whatever reason we would have to revert, we would revert things that did not break anything. So it's better to do it in small chunks, at least that's how I do it. Will that work?

**Comment by dasch** [comment]
I prefer full-featured PRs over a ton of small ones. I'm not interested in half the changes – this only makes sense if we go all the way. But extra points for having nice commits that I can go through one at a time!

**Comment by nijikon** [comment]
I first wanted to clean it up before creating the actual feature, but we can do it in one PR I guess.

**Comment by nguyenquangminh0711** [comment]
Hi @nijikon, it has been a while. The PR is having some conflicts with the master. Do you have any update on this?

**Pull request closed without merging**
