### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by mensfeld**
As discussed, it would be good to add deprec notice for folks plus warning in a post install message

### CODE REVIEW

**Comment by geoff2k** [comment]
What do you think about also adding a post-install message in the gemspec?

Something similar to:

```ruby
spec.post_install_message = %q{
This library is **no longer** actively developed and has been superseded by librdkafka via rdkafka-ruby bindings.

While this library may still receive security patches and bug fixes, it is no longer recommended for production usage.
}
```

**Comment by mensfeld** [comment]
Great idea. Let me add it...

**Review by geoff2k — APPROVED** [review]
:shipit:

**Comment by mensfeld** [comment]
@geoff2k added one more notice in the higher level libs section to indicate correct branches /versions of tools still using ruby-kafka

**Review by geoff2k — APPROVED** [review]
> @geoff2k added one more notice in the higher level libs section to indicate correct branches /versions of tools still using ruby-kafka

Excellent!  Hopefully those that need this information will be able to trip over it in one of the many places it now exists. 😆

**Comment by mensfeld** [comment]
@dasch can we craft a release? :pray:

**Review by dasch — APPROVED** [review]

**Pull request merged**
