### PR TITLE
add kafka 2.3.1

### PR DESCRIPTION
**Pull request by vvuibert**
add kafka 2.3.1
update readme

### CODE REVIEW

**Comment by dasch** [comment]
Can you rebase on master? There was a regression in the test suite.

**Comment by dasch** [comment]
So the Kafka 2.3 build is failing the consumer tests, and I _think_ that's actually because of a regression in Kafka 2.3. Can you check out if that's the case, and if so whether a fix has been released?

**Comment by andrewjamesbrown** [comment]
@dasch I'm seeing some weirdness with consumer-group partition assignments - to me it looks like with Kafka 2.3, there is a re-assignment happening after consumers start processing the events.  We're working on some debugging - will let folks know what we come up with 👍

**Comment by krasnopolsky** [comment]
Running into the consumer-group partition issue with our 2.3.0 cluster, just wanted to reference the kafka issue since I didn't see it here https://issues.apache.org/jira/browse/KAFKA-8653

**Comment by vvuibert** [comment]
I'll update the docker tag once `2.3.1` is released with https://github.com/apache/kafka/pull/7235

**Comment by vvuibert** [comment]
The `2.3.1` docker image is still not out yet

**Pull request closed without merging**
