### PR TITLE
Fix SSL authentication for ruby < 2.4.0

### LINKED ISSUE #741: ssl connection issue for ruby < 2.4
* Version of Ruby: < 2.4
* Version of Kafka: -
* Version of ruby-kafka: >= 0.7.7

Attempting to instanciate a ruby kafka instance with ssl cause an error: `NoMethodError: undefined method `verify_hostname=' for #<OpenSSL::SSL::SSLContext:0x00007fbb1b5a2520>`

`verify_hostname` is supported only from 2.4.0, so the ruby version should be enforced in ruby-kafka or should be supported at the implementation level.

### PR DESCRIPTION
**Pull request by Elyahou**
Should fix #741

### CODE REVIEW

**Comment by dasch** [comment]
Can you explain why the conditional is needed in a comment above the line so future contributors can understand it?

**Comment by Elyahou** [comment]
@dasch Done

**Comment by Elyahou** [comment]
should fix https://github.com/zendesk/ruby-kafka/issues/735 as well

**Comment by dorner** [comment]
@dasch can we get this merged?

**Comment by dasch** [comment]
Thanks 🙏

**Comment by Elyahou** [comment]
@dasch Can you release with this change please ? Thanks

**Pull request merged**
